version: '3.8'
services:
  front_end:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - shared_data:/app/uploads
      - ./front_end:/app
    depends_on:
      - data_backend
      - video_backend
    networks:
      - app-net

  data_backend:
    build:
      context: ./data_backend
      dockerfile: Dockerfile
    networks:
      - app-net
    volumes:
      - ./data_backend:/app
    ports: ["8000:8000"]
  video_backend:
    build:
      context: ./video_backend
      dockerfile: Dockerfile
    volumes:
      - shared_data:/app/uploads
      - ./video_backend:/app
      - /home/makmak/cv2:/home/makmak/cv2:ro
    networks:
      - app-net
    ports: ["8001:8000"]

networks:
  app-net:
    driver: bridge

volumes:
  shared_data: